components:
  schemas:
    ErrorPayload:
      properties:
        message:
          description: Error message
          type: string
        method:
          description: Method type of the request
          type: string
        path:
          description: Request path
          type: string
        reason:
          description: Reason phrase
          type: string
        status:
          description: Relevant HTTP status code
          format: int32
          type: integer
        timestamp:
          description: Timestamp of the error
          type: string
      type: object
    MentalWellness:
      properties:
        mindfulness_exercises:
          $ref: '#/components/schemas/MindfulnessExercises'
        stress_management:
          type: string
      required:
      - mindfulness_exercises
      - stress_management
      type: object
    MindfulnessExercise:
      properties:
        duration:
          type: string
        name:
          type: string
      required:
      - duration
      - name
      type: object
    MindfulnessExercises:
      properties:
        mindfulness_exercises:
          items:
            $ref: '#/components/schemas/MindfulnessExercise'
          type: array
      required:
      - mindfulness_exercises
      type: object
    PhysicalWellness:
      properties:
        exercise:
          type: string
        nutrition:
          type: string
      required:
      - exercise
      - nutrition
      type: object
    WellnessData:
      properties:
        user_id:
          type: string
        wellness_recommendations:
          $ref: '#/components/schemas/WellnessRecommendations'
      required:
      - user_id
      - wellness_recommendations
      type: object
    WellnessRecommendations:
      properties:
        mental_wellness:
          $ref: '#/components/schemas/MentalWellness'
        physical_wellness:
          $ref: '#/components/schemas/PhysicalWellness'
      required:
      - mental_wellness
      - physical_wellness
      type: object
info:
  title: Wellness Recommendation Service
  version: 0.1.0
openapi: 3.1.0
paths:
  /wellness-recommendation:
    get:
      operationId: getWellnessRecommendation
      parameters:
      - in: query
        name: user_id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WellnessData'
          description: Ok
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
          description: Internal server error
servers:
- url: http://wellness-recommendation-service:9090
  variables:
    port:
      default: "9090"
    server:
      default: http://localhost
